# -*- coding: utf-8 -*-
"""HTML Quick Styler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDEU0P7nDrSTaHqaGzb8g5_Z6WUDq09s
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

#===============================================================================
# HTML QUICK-STYLER - ADVANCED VERSION (FIXED)
#===============================================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str="modern") -> Dict[str,str]:
        """Generate a cohesive color palette based on style"""
        palettes = {
            'modern': {
                'primary': '#667eea',
                'secondary': '#764ba2',
                'accent': '#f093fb',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9', # Fixed key naming to match CSS
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'vibrant': {
                'primary': '#ff6b6b',
                'secondary': '#ff8e72',
                'accent': '#f5576c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'ocean': {
                'primary': '#0099cc',
                'secondary': '#006699',
                'accent': '#00ccff',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'forest': {
                'primary': '#27ae60',
                'secondary': '#1e8449',
                'accent': '#52be80',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'sunset': {
                'primary': '#ff8c42',
                'secondary': '#ff6b35',
                'accent': '#ff9751',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'luxury': {
                'primary': '#1a1a1a',
                'secondary': '#333333',
                'accent': '#FFD700',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'creative': {
                'primary': '#9b59b6',
                'secondary': '#8e44ad',
                'accent': '#e74c3c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            },
            'minimal': {
                'primary': '#2c3e50',
                'secondary': '#34495e',
                'accent': '#3498db',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text-primary': '#f1f5f9',
                'text-secondary': '#cbd5e1',
                'border': '#334155'
            }
        }
        return palettes.get(style.lower(), palettes['modern'])

class HTMLPageBuilder:
    """Build styled HTML pages from description"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        """Extract sections from description"""
        sections = []
        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }

        desc_lower = description.lower()
        for section_type, keywords in section_keywords.items():
            for keyword in keywords:
                if keyword in desc_lower:
                    sections.append(section_type)
                    break
        if not sections:
            sections = ['hero', 'features', 'contact', 'footer']
        return sections

    @staticmethod
    def generate_meta_tags(title: str, description: str) -> str:
        """Generate SEO meta tags"""
        meta_tags = f'''  <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{title}</title>
      <meta name="description" content="{description[:160]}">
      <meta name="theme-color" content="#0f172a">
      <meta property="og:title" content="{title}">
      <meta property="og:description" content="{description[:160]}">
      <meta property="og:type" content="website">
      <meta name="twitter:card" content="summary_large_image">
      <meta name="author" content="HTML Quick-Styler">'''
        return meta_tags

    @staticmethod
    def generate_section_html(section_type: str, palette: Dict) -> str:
        """Generate HTML for specific section"""
        sections = {
            'hero': f'''  <section class="hero">
            <div class="hero-content">
              <h1>Welcome to Your Site</h1>
              <p>Create amazing web experiences</p>
              <button class="btn btn-primary">Get Started</button>
            </div>
          </section>''',
            'features': f'''  <section class="features" id="features">
            <h2>Features</h2>
            <div class="features-grid">
              <div class="feature-card">
                <h3>Fast</h3>
                <p>Lightning-quick performance</p>
              </div>
              <div class="feature-card">
                <h3>Secure</h3>
                <p>Enterprise-grade security</p>
              </div>
              <div class="feature-card">
                <h3>Scalable</h3>
                <p>Grow without limits</p>
              </div>
            </div>
          </section>''',
            'about': f''' <section class="about" id="about">
            <div class="about-content">
              <h2>About Us</h2>
              <p>We're passionate about creating beautiful, functional websites that help your business grow.</p>
            </div>
          </section>''',
            'portfolio': f''' <section class="portfolio">
            <h2>Our Work</h2>
            <div class="portfolio-grid">
              <div class="portfolio-item"></div>
              <div class="portfolio-item"></div>
              <div class="portfolio-item"></div>
            </div>
          </section>''',
            'testimonials': f'''  <section class="testimonials">
            <h2>What People Say</h2>
            <div class="testimonials-grid">
              <div class="testimonial">
                <p>"Amazing service!"</p>
                <span>- Client Name</span>
              </div>
              <div class="testimonial">
                <p>"Highly recommended!"</p>
                <span>- Happy Customer</span>
              </div>
            </div>
          </section>''',
            'pricing': f''' <section class="pricing">
            <h2>Pricing Plans</h2>
            <div class="pricing-grid">
              <div class="pricing-card">
                <h3>Starter</h3>
                <p class="price">$29</p>
                <ul><li>Feature 1</li><li>Feature 2</li></ul>
              </div>
              <div class="pricing-card featured">
                <h3>Pro</h3>
                <p class="price">$79</p>
                <ul><li>All Starter</li><li>Feature 3</li></ul>
              </div>
            </div>
          </section>''',
            'contact': f''' <section class="contact" id="contact">
            <h2>Get in Touch</h2>
            <form class="contact-form">
              <input type="text" placeholder="Your Name" required>
              <input type="email" placeholder="Your Email" required>
              <textarea placeholder="Your Message" rows="5" required></textarea>
              <button type="submit" class="btn btn-primary">Send Message</button>
            </form>
          </section>''',
            'footer': f'''  <footer class="footer">
            <div class="footer-content">
              <p>&copy; 2024 Your Company. All rights reserved.</p>
              <div class="footer-links">
                <a href="#privacy">Privacy</a>
                <a href="#terms">Terms</a>
                <a href="#contact">Contact</a>
              </div>
            </div>
          </footer>'''
        }
        return sections.get(section_type, '')

    @staticmethod
    def generate_css(palette: Dict) -> str:
        """Generate comprehensive CSS"""
        css = f''' <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        :root {{
          --primary: {palette['primary']};
          --secondary: {palette['secondary']};
          --accent: {palette['accent']};
          --background: {palette['background']};
          --surface: {palette['surface']};
          --text-primary: {palette['text-primary']};
          --text-secondary: {palette['text-secondary']};
          --border: {palette['border']};
        }}
        body {{
          font-family: 'Segoe UI', sans-serif;
          background: linear-gradient(135deg, var(--background) 0%, var(--surface) 100%);
          color: var(--text-primary);
          line-height: 1.6;
          min-height: 100vh;
        }}
        header {{
          background: rgba(15, 23, 42, 0.95);
          backdrop-filter: blur(10px);
          padding: 1.5rem 2rem;
          position: sticky;
          top: 0;
          z-index: 100;
          border-bottom: 1px solid var(--border);
        }}
        header nav {{
          display: flex;
          justify-content: space-between;
          align-items: center;
          max-width: 1200px;
          margin: 0 auto;
        }}
        header h1 {{
          font-size: 1.8rem;
          background: linear-gradient(135deg, var(--primary), var(--accent));
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }}
        header nav a {{ color: var(--text-secondary); text-decoration: none; margin: 0 1.5rem; transition: color 0.3s; }}
        header nav a:hover {{ color: var(--primary); }}
        main {{ max-width: 1200px; margin: 0 auto; padding: 0 2rem; }}
        section {{ padding: 4rem 0; animation: fadeIn 0.6s ease-in; }}
        @keyframes fadeIn {{ from {{ opacity: 0; transform: translateY(20px); }} to {{ opacity: 1; transform: translateY(0); }} }}
        h1, h2, h3 {{ color: var(--text-primary); margin-bottom: 1rem; }}
        h2 {{ font-size: 2rem; text-align: center; margin-bottom: 2rem; }}
        .hero {{ background: linear-gradient(135deg, var(--primary), var(--secondary)); text-align: center; padding: 6rem 0; }}
        .btn {{ padding: 0.8rem 2rem; border-radius: 8px; border: none; cursor: pointer; font-weight: 600; transition: 0.3s; }}
        .btn-primary {{ background: var(--primary); color: white; }}
        .features-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem; }}
        .feature-card {{ background: rgba(30, 41, 59, 0.8); padding: 2rem; border-radius: 12px; border: 1px solid var(--border); }}
        .portfolio-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; }}
        .portfolio-item {{ aspect-ratio: 1; background: linear-gradient(135deg, var(--primary), var(--secondary)); border-radius: 12px; }}
        .contact-form {{ display: flex; flex-direction: column; gap: 1.5rem; max-width: 600px; margin: 0 auto; }}
        .contact-form input, .contact-form textarea {{ padding: 1rem; border-radius: 8px; background: #1e293b; color: white; border: 1px solid var(--border); }}
        .footer {{ background: #0f172a; padding: 3rem 0; margin-top: 4rem; text-align: center; }}
        </style>'''
        return css

class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, str]:
        palette = ColorPaletteGenerator.generate_palette(style)
        sections = HTMLPageBuilder.extract_sections(description)
        meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)
        sections_html = '\n\n'.join([
            HTMLPageBuilder.generate_section_html(section, palette)
            for section in sections
        ])
        css = HTMLPageBuilder.generate_css(palette)

        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{meta_tags}
{css}
</head>
<body>
  <header>
    <nav>
      <h1>{title}</h1>
      <div>
        <a href="#features">Features</a>
        <a href="#about">About</a>
        <a href="#contact">Contact</a>
      </div>
    </nav>
  </header>
  <main>
{sections_html}
  </main>
</body>
</html>'''
        return html, palette

generation_history = []

def generate_html_page(title: str, description: str, style: str = "modern") -> Tuple[str, str, str]:
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""
    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)
        color_info = f"**Color Palette:**\n- Primary: {palette['primary']}\n- Secondary: {palette['secondary']}\n- Accent: {palette['accent']}"

        generation_history.append({
            'title': title,
            'description': description,
            'html': html_output,
            'palette': palette,
            'timestamp': datetime.now().isoformat()
        })
        return html_output, "✅ HTML pages generated successfully!", color_info
    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_suggestions(style: str) -> str:
    palette = ColorPaletteGenerator.generate_palette(style)
    return f"**Palette for '{style}':**\n- Primary: {palette['primary']}\n- Secondary: {palette['secondary']}\n- Accent: {palette['accent']}"

#========================= GRADIO INTERFACE ==========================

with gr.Blocks(title="HTML Quick-Styler - Advanced Edition") as demo:
    gr.Markdown("# 🎨 HTML Quick-Styler Advanced\n## Professional HTML Page Generator")

    with gr.Tabs():
        with gr.TabItem("🎯 Generate Page"):
            with gr.Row():
                with gr.Column():
                    page_title = gr.Textbox(label="Page Title", value="Modern Portfolio")
                    page_description = gr.Textbox(label="Sections", value="Hero, features, contact", lines=4)
                    color_style = gr.Dropdown(["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"], value="modern", label="Style")
                    generate_btn = gr.Button("✨ Generate HTML", variant="primary")
                with gr.Column():
                    html_output = gr.Code(language="html", label="Output", lines=20)
                    status_msg = gr.Markdown()
                    color_info = gr.Markdown()

            generate_btn.click(generate_html_page, inputs=[page_title, page_description, color_style], outputs=[html_output, status_msg, color_info])

        with gr.TabItem("👁️ Live Preview"):
            preview_btn = gr.Button("Refresh Preview")
            preview_output = gr.HTML("<p style='text-align:center;'>No preview loaded.</p>")
            preview_btn.click(lambda x: x, inputs=[html_output], outputs=[preview_output])

        with gr.TabItem("🎨 Color Palettes"):
            style_selection = gr.Radio(["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"], label="Style", value="modern")
            palette_btn = gr.Button("Get Palette")
            palette_display = gr.Markdown()
            palette_btn.click(get_color_suggestions, inputs=[style_selection], outputs=[palette_display])

        with gr.TabItem("📄 Templates"):
            with gr.Row():
                portfolio_btn = gr.Button("Portfolio Template")
                saas_btn = gr.Button("SaaS Template")

            portfolio_btn.click(lambda: ("Portfolio", "Hero, features, portfolio, contact", "modern"), outputs=[page_title, page_description, color_style])
            saas_btn.click(lambda: ("SaaS Page", "Hero, features, pricing, footer", "vibrant"), outputs=[page_title, page_description, color_style])

demo.launch()