# -*- coding: utf-8 -*-
"""HTML Quick Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDEU0P7nDrSTaHqaGzb8g5_Z6WUDq09s
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

#===============================================================================
# HTML QUICK-STYLER - ADVANCED VERSION (FIXED)
#===============================================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""
    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        palettes = {
            'modern': {'primary': '#667eea', 'secondary': '#764ba2', 'accent': '#f093fb', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'vibrant': {'primary': '#ff6b6b', 'secondary': '#ff8e72', 'accent': '#f5576c', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'ocean': {'primary': '#0099cc', 'secondary': '#006699', 'accent': '#00ccff', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'forest': {'primary': '#27ae60', 'secondary': '#1e8449', 'accent': '#52be80', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'sunset': {'primary': '#ff8c42', 'secondary': '#ff6b35', 'accent': '#ff9751', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'luxury': {'primary': '#d4af37', 'secondary': '#1a1a1a', 'accent': '#FFD700', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'creative': {'primary': '#9b59b6', 'secondary': '#8e44ad', 'accent': '#e74c3c', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'},
            'minimal': {'primary': '#64748b', 'secondary': '#475569', 'accent': '#3b82f6', 'background': '#0f172a', 'surface': '#1e293b', 'text-primary': '#f1f5f9', 'text-secondary': '#cbd5e1', 'border': '#334155'}
        }
        return palettes.get(style.lower(), palettes['modern'])

class HTMLPageBuilder:
    """Build styled HTML pages from description"""
    @staticmethod
    def extract_sections(description: str) -> List[str]:
        sections = []
        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }
        desc_lower = description.lower()
        for section_type, keywords in section_keywords.items():
            if any(kw in desc_lower for kw in keywords):
                sections.append(section_type)
        return sections if sections else ['hero', 'features', 'contact', 'footer']

    @staticmethod
    def generate_meta_tags(title: str, description: str) -> str:
        return f'''<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description[:160]}">
<meta property="og:title" content="{title}">
<meta property="og:type" content="website">'''

    @staticmethod
    def generate_section_html(section_type: str) -> str:
        sections = {
            'hero': '<section class="hero"><div class="hero-content"><h1>Welcome</h1><p>Create amazing web experiences</p><button class="btn btn-primary">Get Started</button></div></section>',
            'features': '<section class="features" id="features"><h2>Features</h2><div class="features-grid"><div class="feature-card"><h3>Fast</h3><p>Lightning performance</p></div><div class="feature-card"><h3>Secure</h3><p>Enterprise grade</p></div><div class="feature-card"><h3>Scalable</h3><p>Grow without limits</p></div></div></section>',
            'about': '<section class="about" id="about"><h2>About Us</h2><p>We create beautiful, functional websites.</p></section>',
            'portfolio': '<section class="portfolio"><h2>Our Work</h2><div class="portfolio-grid"><div class="portfolio-item"></div><div class="portfolio-item"></div><div class="portfolio-item"></div></div></section>',
            'testimonials': '<section class="testimonials"><h2>Reviews</h2><div class="testimonials-grid"><div class="testimonial"><p>"Amazing!"</p><span>- Client</span></div></div></section>',
            'pricing': '<section class="pricing"><h2>Pricing</h2><div class="pricing-grid"><div class="pricing-card"><h3>Pro</h3><p class="price">$79</p></div></div></section>',
            'contact': '<section class="contact" id="contact"><h2>Contact</h2><form class="contact-form"><input type="text" placeholder="Name"><input type="email" placeholder="Email"><button type="submit" class="btn btn-primary">Send</button></form></section>',
            'footer': '<footer class="footer"><p>&copy; 2026 Company. All rights reserved.</p></footer>'
        }
        return sections.get(section_type, '')

    @staticmethod
    def generate_css(palette: Dict) -> str:
        return f'''<style>
:root {{
    --primary: {palette['primary']}; --secondary: {palette['secondary']}; --accent: {palette['accent']};
    --background: {palette['background']}; --surface: {palette['surface']};
    --text-primary: {palette['text-primary']}; --text-secondary: {palette['text-secondary']}; --border: {palette['border']};
}}
body {{ font-family: sans-serif; background: var(--background); color: var(--text-primary); margin: 0; }}
header {{ background: rgba(15, 23, 42, 0.9); padding: 1rem; position: sticky; top: 0; border-bottom: 1px solid var(--border); }}
nav {{ display: flex; justify-content: space-between; max-width: 1200px; margin: 0 auto; }}
section {{ padding: 4rem 2rem; max-width: 1200px; margin: 0 auto; }}
.hero {{ text-align: center; background: linear-gradient(var(--primary), var(--secondary)); padding: 6rem 2rem; }}
.features-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem; }}
.feature-card {{ background: var(--surface); padding: 2rem; border-radius: 12px; border: 1px solid var(--border); }}
.btn {{ padding: 0.8rem 2rem; border-radius: 8px; border: none; cursor: pointer; background: var(--primary); color: white; }}
.contact-form {{ display: flex; flex-direction: column; gap: 1rem; max-width: 500px; margin: 0 auto; }}
input {{ padding: 0.8rem; background: var(--surface); border: 1px solid var(--border); color: white; }}
</style>'''

class HTMLGenerationEngine:
    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, Dict]:
        palette = ColorPaletteGenerator.generate_palette(style)
        sections = HTMLPageBuilder.extract_sections(description)
        meta = HTMLPageBuilder.generate_meta_tags(title, description)
        css = HTMLPageBuilder.generate_css(palette)

        sections_html = ""
        for s in sections:
            sections_html += HTMLPageBuilder.generate_section_html(s) + "\n"

        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    {meta}
    {css}
</head>
<body>
    <header><nav><h1>{title}</h1><div><a href="#features" style="color:white; margin-left:20px;">Features</a><a href="#contact" style="color:white; margin-left:20px;">Contact</a></div></nav></header>
    <main>{sections_html}</main>
</body>
</html>'''
        return html, palette

def generate_html_page(title: str, description: str, style: str = "modern"):
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""
    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)
        color_info = f"**Palette:** Primary: {palette['primary']} | Secondary: {palette['secondary']}"
        return html_output, "✅ Generated successfully!", color_info
    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_suggestions(style: str) -> str:
    p = ColorPaletteGenerator.generate_palette(style)
    return f"**{style.capitalize()} Palette:**\n- Primary: {p['primary']}\n- Secondary: {p['secondary']}\n- Accent: {p['accent']}"

#========================= GRADIO INTERFACE ==========================

with gr.Blocks(title="HTML Quick-Styler") as demo:
    gr.Markdown("# 🎨 HTML Quick-Styler Advanced")

    with gr.Tabs():
        with gr.Tab("🎯 Generate Page"):
            with gr.Row():
                with gr.Column():
                    page_title = gr.Textbox(label="Page Title", value="My Startup")
                    page_desc = gr.Textbox(label="Description", value="Hero, features, and contact form", lines=4)
                    style_drop = gr.Dropdown(["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"], value="modern", label="Style")
                    gen_btn = gr.Button("✨ Generate", variant="primary")
                with gr.Column():
                    html_out = gr.Code(label="HTML/CSS Output", language="html", lines=15)
                    status = gr.Markdown()
                    colors = gr.Markdown()

            gen_btn.click(generate_html_page, inputs=[page_title, page_desc, style_drop], outputs=[html_out, status, colors])

        with gr.Tab("👁️ Preview"):
            preview_html = gr.HTML("<p style='text-align:center;'>Generate a page first to see preview</p>")
            pre_btn = gr.Button("Refresh Preview")
            pre_btn.click(lambda x: x, inputs=[html_out], outputs=[preview_html])

        with gr.Tab("📄 Templates"):
            with gr.Row():
                port_btn = gr.Button("Portfolio")
                saas_btn = gr.Button("SaaS")

            port_btn.click(lambda: ("My Portfolio", "Hero, portfolio gallery, about me, contact", "creative"), outputs=[page_title, page_desc, style_drop])
            saas_btn.click(lambda: ("SaaS Landing", "Hero, features, pricing, testimonials, footer", "vibrant"), outputs=[page_title, page_desc, style_drop])

demo.launch()